class CustomMail < ::ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[CustomMail, ActiveRecord_Relation, Integer]

  module GeneratedAttributeMethods
    def id: () -> Integer

    def id=: (Integer) -> Integer

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ Integer?, Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> Integer?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> Array[Integer?]?

    def id_previously_was: () -> Integer?

    def id_before_last_save: () -> Integer?

    def id_change_to_be_saved: () -> Array[Integer?]?

    def id_in_database: () -> Integer?

    def saved_change_to_id: () -> Array[Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def subject: () -> String?

    def subject=: (String?) -> String?

    def subject?: () -> bool

    def subject_changed?: () -> bool

    def subject_change: () -> [ String?, String? ]

    def subject_will_change!: () -> void

    def subject_was: () -> String?

    def subject_previously_changed?: () -> bool

    def subject_previous_change: () -> Array[String?]?

    def subject_previously_was: () -> String?

    def subject_before_last_save: () -> String?

    def subject_change_to_be_saved: () -> Array[String?]?

    def subject_in_database: () -> String?

    def saved_change_to_subject: () -> Array[String?]?

    def saved_change_to_subject?: () -> bool

    def will_save_change_to_subject?: () -> bool

    def restore_subject!: () -> void

    def clear_subject_change: () -> void

    def content: () -> String?

    def content=: (String?) -> String?

    def content?: () -> bool

    def content_changed?: () -> bool

    def content_change: () -> [ String?, String? ]

    def content_will_change!: () -> void

    def content_was: () -> String?

    def content_previously_changed?: () -> bool

    def content_previous_change: () -> Array[String?]?

    def content_previously_was: () -> String?

    def content_before_last_save: () -> String?

    def content_change_to_be_saved: () -> Array[String?]?

    def content_in_database: () -> String?

    def saved_change_to_content: () -> Array[String?]?

    def saved_change_to_content?: () -> bool

    def will_save_change_to_content?: () -> bool

    def restore_content!: () -> void

    def clear_content_change: () -> void

    def sent: () -> bool?

    def sent=: (bool?) -> bool?

    def sent?: () -> bool

    def sent_changed?: () -> bool

    def sent_change: () -> [ bool?, bool? ]

    def sent_will_change!: () -> void

    def sent_was: () -> bool?

    def sent_previously_changed?: () -> bool

    def sent_previous_change: () -> Array[bool?]?

    def sent_previously_was: () -> bool?

    def sent_before_last_save: () -> bool?

    def sent_change_to_be_saved: () -> Array[bool?]?

    def sent_in_database: () -> bool?

    def saved_change_to_sent: () -> Array[bool?]?

    def saved_change_to_sent?: () -> bool

    def will_save_change_to_sent?: () -> bool

    def restore_sent!: () -> void

    def clear_sent_change: () -> void

    def created_at: () -> ActiveSupport::TimeWithZone

    def created_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: () -> bool

    def created_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: () -> bool

    def created_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> Array[ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: () -> bool

    def will_save_change_to_created_at?: () -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def updated_at: () -> ActiveSupport::TimeWithZone

    def updated_at=: (ActiveSupport::TimeWithZone) -> ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: () -> bool

    def updated_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: () -> bool

    def updated_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> Array[ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: () -> bool

    def will_save_change_to_updated_at?: () -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def user_id: () -> Integer?

    def user_id=: (Integer?) -> Integer?

    def user_id?: () -> bool

    def user_id_changed?: () -> bool

    def user_id_change: () -> [ Integer?, Integer? ]

    def user_id_will_change!: () -> void

    def user_id_was: () -> Integer?

    def user_id_previously_changed?: () -> bool

    def user_id_previous_change: () -> Array[Integer?]?

    def user_id_previously_was: () -> Integer?

    def user_id_before_last_save: () -> Integer?

    def user_id_change_to_be_saved: () -> Array[Integer?]?

    def user_id_in_database: () -> Integer?

    def saved_change_to_user_id: () -> Array[Integer?]?

    def saved_change_to_user_id?: () -> bool

    def will_save_change_to_user_id?: () -> bool

    def restore_user_id!: () -> void

    def clear_user_id_change: () -> void
  end
  include GeneratedAttributeMethods

  def sender: () -> User
  def sender=: (User?) -> User?
  def reload_sender: () -> User?
  def build_sender: (untyped) -> User
  def create_sender: (untyped) -> User
  def create_sender!: (untyped) -> User
  module GeneratedAssociationMethods
  end
  include GeneratedAssociationMethods

  module GeneratedRelationMethods
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[CustomMail, Integer]
    include Enumerable[CustomMail]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[CustomMail, Integer]
  end
end
