extensions:
  health_check: {}

receivers:
  otlp:
    protocols:
      http:

processors:
  batch:
  transform:
    trace_statements:
      - context: span
        statements:
        - truncate_all(attributes, 4095)
        - truncate_all(resource.attributes, 4095)

exporters:
  logging:

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

  otlp:
    endpoint: https://otlp.nr-data.net:4318
    headers:
      "api-key": $NEW_RELIC_API_KEY

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform, batch]
      exporters: [logging, jaeger, otlp]
