// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import GroupsController from './groups_controller';
import ProjectsController from './projects_controller';

application.register('groups', GroupsController);
application.register('projects', ProjectsController);
