// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AssignmentController from "./assignment_controller.js"
application.register("assignment", AssignmentController)

import ContestController from "./contest_controller.js"
application.register("contest", ContestController)

import ExploreController from "./explore_controller.js"
application.register("explore", ExploreController)

import GroupsController from "./groups_controller.js"
application.register("groups", GroupsController)

import NotificationsController from "./notifications_controller.js"
application.register("notifications", NotificationsController)

import ProjectsController from "./projects_controller.js"
application.register("projects", ProjectsController)

import SearchBarController from "./search_bar_controller.js"
application.register("search-bar", SearchBarController)

import ShareController from "./share_controller.js"
application.register("share", ShareController)
