---
name: rails-dom-testing
version: '2.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 280d44d7671abfa909f2966fbef94bca5be082de
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
