documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'

javascript:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.js'
          - '**/*.jsx'
          - '**/*.ts'
          - '**/*.tsx'

ruby:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.rb'
          - 'Gemfile'
          - 'Gemfile.lock'

docker:
  - changed-files:
      - any-glob-to-any-file:
          - 'Dockerfile'
          - 'docker-compose*.yml'
          - 'docker-compose*.yaml'
          - '.docker/**'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'
          - 'yarn.lock'
          - 'Gemfile'
          - 'Gemfile.lock'

infra:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'
          - '.github/dependabot.yml'