version: "2"
plugins:
  rubocop:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-5"

ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.module"

exclude_paths:
- config/
- db/
- vendor/
- public/bootstrap-3.3.7/
- public/external/
- test/
- tmp/
