image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000 # client
    onOpen: open-browser
  - port: 5432 # postgres
    onOpen: ignore
  - port: 6379 # redis
    onOpen: ignore
  - port: 8982 # sunspot solr
    onOpen: ignore
  - port: 7982
    onOpen: ignore

tasks:
  - name: CircuitVerse
    before: >
      redis-server --daemonize yes
    # init is not executed for prebuilt workspaces and restarts,
    # so we should put all the heavy initialization here
    init: >
      echo "Installing rvm" &&
      rvm autolibs disable &&
      rvm install 2.6.5 &&
      echo "Installing ruby bundler" &&
      gem install bundler &&
      echo "Installing ruby dependencies" &&
      bundle install --without production --path vendor/bundle &&
      echo "Installing yarn dependencies" &&
      yarn &&
      cp config/database.example.yml config/database.yml &&
      echo "Creating postgres user" &&
      createuser -s postgres &&
      echo "Setting up database" &&
      bundle exec rails db:create &&
      bundle exec rails db:schema:load &&
      bundle exec rails db:migrate &&
      bundle exec rails db:seed
    command: >
      bundle exec rake sunspot:solr:start &&
      bundle exec rails server &&
      ./bin/webpack-dev-server

github:
    prebuilds:
        pullRequestsFromForks: true

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.1:DO6k4GCpqhwZcKo+jY9xjQ==
    - misogi.ruby-rubocop@0.8.3:ptn+lTc9xnktGhPEYKIf2w==
    - adamwalzer.scss-lint@0.1.10:+toK2RNvnvWcaAP+81LKWg==
    - rebornix.ruby@0.27.0:b86Iqz+ryuS7Nr77EyIClA==
    - castwide.solargraph@0.21.1:kJz6aC6XZbI/EeYHUPNCmQ==
    - wingrunr21.vscode-ruby@0.27.0:VymtAvJQnv5jef/FsPtqJw==
