image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      rvm autolibs disable &&
      rvm install 3.0.3 &&
      nvm install 14 &&
      gem install bundler &&
      cp config/database.example.yml config/database.yml &&
      createuser -s postgres &&
      (redis-server &) &&
      bundle install --without production --path vendor/bundle &&
      yarn &&
      bundle exec rails db:create &&
      bundle exec rails db:schema:load &&
      bundle exec rails db:migrate &&
      bundle exec rails db:seed
    command: >
      sleep 5 &&
      redis-server --daemonize yes &&
      bundle install --without production --path vendor/bundle &&
      yarn &&
      bundle exec rails db:create &&
      bundle exec rails db:schema:load &&
      bundle exec rails db:migrate &&
      bundle exec rake sunspot:solr:start &&
      bundle exec rails db:seed &&
      bin/dev
github:
    prebuilds:
        pullRequestsFromForks: true

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.1:DO6k4GCpqhwZcKo+jY9xjQ==
    - misogi.ruby-rubocop@0.8.3:ptn+lTc9xnktGhPEYKIf2w==
    - adamwalzer.scss-lint@0.1.10:+toK2RNvnvWcaAP+81LKWg==
    - rebornix.ruby@0.27.0:b86Iqz+ryuS7Nr77EyIClA==
    - castwide.solargraph@0.21.1:kJz6aC6XZbI/EeYHUPNCmQ==
    - wingrunr21.vscode-ruby@0.27.0:VymtAvJQnv5jef/FsPtqJw==
