image:
  file: .gitpod.Dockerfile

ports:
  - name: Web App
    port: 3000
    onOpen: open-preview
  - port: 3001-9000
    onOpen: ignore
tasks:
  - init: >
      cp ./.gitpod.vscode.settings .vscode/settings.json &&
      rvm autolibs disable &&
      rvm install 3.2.0 &&
      nvm install 14 &&
      gem install bundler &&
      cp config/database.example.yml config/database.yml &&
      createuser -s postgres &&
      (redis-server &) &&
      bundle install --without production --path vendor/bundle &&
      yarn &&
      bundle exec rails db:create &&
      bundle exec rails db:schema:load &&
      bundle exec rails db:migrate &&
      bundle exec rails db:seed
    command: >
      sleep 5 &&
      redis-server --daemonize yes &&
      bundle install --without production --path vendor/bundle &&
      yarn &&
      bundle exec rails db:create &&
      bundle exec rails db:schema:load &&
      bundle exec rails db:migrate &&
      bundle exec rails db:seed &&
      bin/dev
github:
    prebuilds:
        pullRequestsFromForks: true

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - https://github.com/tanmoysrt/vsix-extension/raw/main/ruby-rubocop-revived-0.9.5.vsix
    - rebornix.ruby
    - castwide.solargraph
    - wingrunr21.vscode-ruby
    - https://github.com/tanmoysrt/vsix-extension/raw/main/vscode-rdbg-0.2.1.vsix