image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000 #client
    onOpen: open-preview

tasks:
  - name: CircuitVerse
    init: >
      rvm autolibs disable &&
      rvm install 2.6.5 &&
      gem install bundler
      bundle install --without production --path vendor/bundle &&
      yarn &&
      cp config/database.example.yml config/database.yml &&
      createuser -s postgres &&
      bundle exec rails db:create &&
      bundle exec rails db:schema:load &&
      bundle exec rails db:migrate &&
      bundle exec rails db:seed
    command: >
      redis-server --daemonize yes &&
      bundle exec rake sunspot:solr:start &&
      bundle exec rails server &&
      ./bin/webpack-dev-server

github:
    prebuilds:
        pullRequestsFromForks: true

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.1:DO6k4GCpqhwZcKo+jY9xjQ==
    - misogi.ruby-rubocop@0.8.3:ptn+lTc9xnktGhPEYKIf2w==
    - adamwalzer.scss-lint@0.1.10:+toK2RNvnvWcaAP+81LKWg==
    - rebornix.ruby@0.27.0:b86Iqz+ryuS7Nr77EyIClA==
    - castwide.solargraph@0.21.1:kJz6aC6XZbI/EeYHUPNCmQ==
    - wingrunr21.vscode-ruby@0.27.0:VymtAvJQnv5jef/FsPtqJw==
