version: '3.1'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: circuitverse_production
      POSTGRES_PASSWORD: postgres
  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq -e production -q default -q mailers -d -L tmp/sidekiq.log
    volumes:
      - .:/circuitverse
      - ./config/database.docker.yml:/circuitverse/config/database.yml
    environment:
      REDIS_URL: "redis://redis:6379/0"
  web:
    build: .
    entrypoint: /circuitverse/bin/docker_run
    volumes:
      - .:/circuitverse
      - ./config/database.docker.yml:/circuitverse/config/database.yml
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
    environment:
      REDIS_URL: "redis://redis:6379/0"
      CIRCUITVERSE_USE_SOLR: "false"
  redis:
    image: redis
# volumes:
  # app:
  # public
