module Commontator
end
class Commontator::Comment::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Commontator::Subscription::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ActsAsVotable::Vote::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
module Mailkick
end
module FriendlyId
end
module ActsAsVotable
end
module ActiveStorage
end
class ActiveStorage::Record < ActiveRecord::Base
end
class ActiveStorage::VariantRecord::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ActiveStorage::Attachment::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ApplicationRecord < ActiveRecord::Base
end
module Ahoy
end
class Ahoy::Event::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Tagging::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Project::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class NoticedNotification::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class FriendlyId::Slug::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Star::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class User::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Collaboration::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Tag::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Assignment::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class GroupMember::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class PendingInvitation::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Grade::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ForumThread::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ForumPost::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ForumSubscription::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Group::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class PushSubscription::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ActiveRecord::Associations::CollectionProxy < ActiveRecord::Relation
end
class ActiveRecord::Relation < Object
end
module ActiveRecord::Associations
end
