class ProfileDecorator < SimpleDelegator
  def profile: () -> User
  def member_since: () -> Time
  def educational_institute: () -> string
  def country_name: () -> string
  def mail_subscription: () -> ("Subscribed" | "Not Subscribed")
  def total_circuits: () -> string
end
