name: 🐞 Bug Report
description: Create a report to help us improve
title: "🐞 Bug: [Title]"
labels: ["🐞 bug", "pending triage"]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues.
          required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Is the faced issue/bug related to the Vue simulator?
      description: Describe the issue you have faced in detail.
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Used Vue simulator with or without backend?
      description: Provide a clear and concise description of how you used the simulator.
      options:
        - 'With Backend'
        - 'Without Backend'
        - 'With circuitverse.org'
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Is the bug present only on the dev server, the build, or both?
      description: Describe where the issue/bug occurs.
      options:
        - 'Dev Server Only'
        - 'Build Only'
        - 'Both'
    validations:
      required: false

  - type: textarea
    attributes:
      label: Device Information
      description: |
        Examples:
          - **OS**: Ubuntu 20.04
          - **Browser**: Chrome
          - **Version**: 89
      render: markdown
    validations:
      required: false

  - type: input
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Are you working on this issue?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
