blank_issues_enabled: true
contact_links:
  - name: Have any issues to discuss regarding CircuitVerse?
    url: https://join.slack.com/t/circuitverse-team/shared_invite/enQtNjc4MzcyNDE5OTA3LTdjYTM5NjFiZWZlZGI2MmU1MmYzYzczNmZlZDg5MjYxYmQ4ODRjMjQxM2UyMWI5ODUzODQzMDU2ZDEzNjI4NmE
    about: Join us on Slack and meet members, contributors and the owners!
