blank_issues_enabled: true
contact_links:
  - name: Have any issues to discuss regarding CircuitVerse?
    url: https://join.slack.com/t/circuitverse-team/shared_invite/zt-p6bgler9-~8vWvsKmL9lZeYg4pP9hwQ
    about: Join us on Slack and meet members, contributors and the owners!
