class Users::RegistrationsController < Devise::RegistrationsController
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params: () -> untyped

  private

  def check_captcha: () -> (untyped | nil)
end
