class AssignmentMailer < ApplicationMailer
  def new_assignment_email: (untyped user, untyped assignment) -> (nil | untyped)

  def update_assignment_email: (untyped user, untyped assignment) -> (nil | untyped)
end
