version: "3.1"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: circuitverse_development
      POSTGRES_PASSWORD: postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: "redis://redis:6379/0"
      CIRCUITVERSE_USE_SOLR: "false"
      DOCKER_ENVIRONMENT: "true"
      DEV_CONTAINER: "true"
    volumes:
    - ..:/workspaces/CircuitVerse
    command: sleep infinity
  redis:
    image: redis:7.0-alpine
