default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV.fetch('DATABASE_USER', 'postgres') %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: circuitverse_development

test:
  <<: *default
  database: circuitverse_test

production:
  <<: *default
  database: circuitverse_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>