default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: db
  port: 5432
  pool: <%= ENV.fetch("DB_POOL") { ENV.fetch("RAILS_MAX_THREADS", 5) } %>
  checkout_timeout: <%= ENV.fetch("DB_CHECKOUT_TIMEOUT", 5.0) %>
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 10) %>
  variables:
    lock_timeout: <%= ENV.fetch("DB_LOCK_TIMEOUT", "3000") %>
    idle_in_transaction_session_timeout: <%= ENV.fetch("DB_IDLE_TX_TIMEOUT", "10000") %>

development:
  <<: *default
  database: circuitverse_development

test:
  <<: *default
  database: circuitverse_test
  pool: <%= ENV.fetch("TEST_DB_POOL", 5) %>