# frozen_string_literal: true

ruby ">=2.3.1"
source "https://rubygems.org"

# Middleman
gem "middleman", "~>4.3"
gem "middleman-autoprefixer", "~> 2.7"
gem "middleman-sprockets", "~> 4.1"
gem "middleman-syntax", "~> 3.0"
gem "nokogiri", "~> 1.10.8"
gem "redcarpet", "~> 3.4.0"
gem "rouge", "~> 2.0.5"
gem "sass"
