name: Crowdin Localization

on:
  # Run on pushes to main branch
  push:
    branches: [ master ]
  # Run on schedule (twice a week - Monday and Thursday at 00:00 UTC)
  schedule:
    - cron: '0 0 * * 1,4'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin Action
        uses: crowdin/github-action@v2
        with:
          # Upload source files to Crowdin
          upload_sources: true
          
          # Upload existing translations to Crowdin for reference
          upload_translations: true
          
          # Download the latest translations from Crowdin
          download_translations: true
          
          # Name of the branch where Crowdin will push translations
          localization_branch_name: l10n_crowdin_translations
          
          # Create pull request with translations
          create_pull_request: true
          pull_request_title: 'New Crowdin Translations'
          pull_request_body: 'This PR contains the latest translations from Crowdin'
          pull_request_labels: 'localization'
          
          # Base branch for the pull request
          pull_request_base_branch_name: 'master'
          
          # Skip untranslated strings
          skip_untranslated_strings: true
          
          # Skip files that have no translations
          skip_untranslated_files: false
          
          # Commit message for translation updates
          commit_message: 'chore: update translations from Crowdin'
          
          # Configuration file path
          config: 'crowdin.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
