name: Deploy to Server
on:
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  build-production:
    uses: CircuitVerse/CircuitVerse/.github/workflows/docker-publish.yml@master

  deploy-production:
    needs: build-production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment:
      name: production
      url: https://staging.circuitverse.org

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'

      - name: Install kamal
        run: gem install kamal

      - name: Deploy with kamal
        run: |
          kamal lock release
          kamal accessory boot yosys2digitaljs-server || true
          kamal traefik boot || true
          kamal redeploy -vvvv --skip_push
        env:
          RAILS_SERVE_STATIC_FILES: true
          AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
          KAMAL_GHCR_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
