name: Deploy to Server
on: workflow_dispatch
concurrency: production

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: cv-mrsk.vaibhavupreti.me

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'

      - name: Install mrsk
        run: gem install mrsk

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Release acquired locks
        run: mrsk lock release
        env:
          RAILS_SERVE_STATIC_FILES: true
          AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
          MRSK_GHCR_REGISTRY_PASSWORD: ${{ secrets.MRSK_GHCR_REGISTRY_PASSWORD }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}

      - name: Deploy with mrsk
        run: mrsk deploy -vvvv --skip_push
