name: docs

on:
  push:
    branches:
      - setting-up-webpacker

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: jsdocs-action
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./public/src
          output_dir: ./out
          config_file: ./conf.json
          template: better-docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out