name: docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: jsdocs-dep
        run: npm install
      - name: jsdocs-action
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./simulator/src
          recurse: true
          output_dir: ./out
          config_file: ./conf.json
          template: better-docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: simulator-docs.circuitverse.org
