name: Documentation

 # Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ Documentation ]

 jobs:
  build:
    runs-on: ubuntu-latest

     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

     # Runs a single command using the runners shell
    - name: Build
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./public/src/**
        output_dir: ./out
        config_file: ./conf.json
        template: better-docs
        front_page: README.md
    # Runs a set of commands using the runners shell
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
