jobs:
  percy-tests:

    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request_target' && contains(toJson(github.event.pull_request.labels), '"name":"check-visual-regression"')) }}

    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"

    steps:
      - name: Check out base repo code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run tests with Percy
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npx percy exec -- bundle exec rspec