name: Welcome
on:
  pull_request:
    types: [closed]
  issues:
    types: [opened]
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/welcome@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIRST_ISSUE: |
            👋 @{{ author }}
             Thanks for opening your first issue here! 

#           FIRST_PR: |
#             👋 @{{ author }}
#             Thanks for opening this pull request! Please check out our contributing guidelines.

          FIRST_PR_MERGED: |
            🎉 @{{ author }}
            Congrats on merging your first pull request! You can checkout the contribution guidelines [here](https://github.com/CircuitVerse/CircuitVerse/blob/master/CONTRIBUTING.md).
