class CircuitElementsImageUploader < CarrierWave::Uploader::Base
  # Override the directory where uploaded files will be stored.
  # This is a sensible default for uploaders that are meant to be mounted:
  def store_dir: () -> ::String

  # Add a white list of extensions which are allowed to be uploaded.
  # For images you might use something like this:
  def extension_whitelist: () -> ::Array["jpg" | "jpeg" | "gif" | "png" | "svg"]
end
