class ImagePreviewUploader < CarrierWave::Uploader::Base
  # Override the directory where uploaded files will be stored.
  # This is a sensible default for uploaders that are meant to be mounted:
  def store_dir: () -> ::String

  # Provide a default URL as a default if there hasn't been a file uploaded:
  def default_url: (*untyped _args) -> untyped
end
